default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: bleater-dev
  host: db
  username: postgres
  password:

test:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] ||= 'db' %>
  username: <%= ENV['POSTGRES_HOST'] ||= 'postgres' %>
  password: <%= ENV['POSTGRES_HOST'] ||= '' %>
  database: bleater-test

production:
  <<: *default
  database: bleater
  username: bleater
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
